spring.application.name=api-gateway
server.port=8000

spring.cloud.gateway.mvc.routes[0].id=ingestion-service-route
spring.cloud.gateway.mvc.routes[0].uri=${INGESTION_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/ingest/**

spring.cloud.gateway.mvc.routes[1].id=wallet-service-route
spring.cloud.gateway.mvc.routes[1].uri=${WALLET_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/accounts/**
