spring.application.name=wallet-service
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
server.port=8082
spring.threads.virtual.enabled=true

# Kafka Connection
spring.kafka.bootstrap-servers=${KAFKA_BROKERS}

# Redis Connection
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}