spring.application.name=wallet-service
server.port=8082
spring.threads.virtual.enabled=true

# Kafka Connection
spring.kafka.bootstrap-servers=${KAFKA_BROKERS}

# Redis Connection
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}