spring.application.name=ingestion-service
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
server.port=8081
spring.threads.virtual.enabled=true
spring.kafka.bootstrap-servers=${KAFKA_BROKERS}